// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: authorization.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentityAuditLog = `-- name: CreateIdentityAuditLog :exec
INSERT INTO identity_audit_logs (
    id,
    foundation_id,
    school_id,
    actor_user_id,
    actor_role,
    action,
    module,
    entity_type,
    entity_id,
    old_values_json,
    new_values_json,
    metadata_json,
    ip_address,
    user_agent,
    request_id,
    correlation_id,
    occurred_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
`

type CreateIdentityAuditLogParams struct {
	ID            uuid.UUID          `json:"id"`
	FoundationID  uuid.UUID          `json:"foundation_id"`
	SchoolID      *uuid.UUID         `json:"school_id"`
	ActorUserID   *uuid.UUID         `json:"actor_user_id"`
	ActorRole     *string            `json:"actor_role"`
	Action        string             `json:"action"`
	Module        string             `json:"module"`
	EntityType    string             `json:"entity_type"`
	EntityID      uuid.UUID          `json:"entity_id"`
	OldValuesJson []byte             `json:"old_values_json"`
	NewValuesJson []byte             `json:"new_values_json"`
	MetadataJson  []byte             `json:"metadata_json"`
	IpAddress     *string            `json:"ip_address"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	RequestID     string             `json:"request_id"`
	CorrelationID string             `json:"correlation_id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateIdentityAuditLog(ctx context.Context, arg CreateIdentityAuditLogParams) error {
	_, err := q.db.Exec(ctx, createIdentityAuditLog,
		arg.ID,
		arg.FoundationID,
		arg.SchoolID,
		arg.ActorUserID,
		arg.ActorRole,
		arg.Action,
		arg.Module,
		arg.EntityType,
		arg.EntityID,
		arg.OldValuesJson,
		arg.NewValuesJson,
		arg.MetadataJson,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
		arg.CorrelationID,
		arg.OccurredAt,
	)
	return err
}

const createUserRoleAssignment = `-- name: CreateUserRoleAssignment :one
INSERT INTO user_role_assignments (
    id,
    user_id,
    role_id,
    foundation_id,
    school_id,
    class_id,
    student_id,
    employee_id,
    subject_id,
    scope_json,
    starts_at,
    ends_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, user_id, role_id, foundation_id, school_id, class_id, student_id,
    employee_id, subject_id, scope_json, is_active, starts_at, ends_at, created_at, updated_at
`

type CreateUserRoleAssignmentParams struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	RoleID       uuid.UUID          `json:"role_id"`
	FoundationID uuid.UUID          `json:"foundation_id"`
	SchoolID     *uuid.UUID         `json:"school_id"`
	ClassID      *uuid.UUID         `json:"class_id"`
	StudentID    *uuid.UUID         `json:"student_id"`
	EmployeeID   *uuid.UUID         `json:"employee_id"`
	SubjectID    *uuid.UUID         `json:"subject_id"`
	ScopeJson    []byte             `json:"scope_json"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	EndsAt       pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateUserRoleAssignment(ctx context.Context, arg CreateUserRoleAssignmentParams) (UserRoleAssignment, error) {
	row := q.db.QueryRow(ctx, createUserRoleAssignment,
		arg.ID,
		arg.UserID,
		arg.RoleID,
		arg.FoundationID,
		arg.SchoolID,
		arg.ClassID,
		arg.StudentID,
		arg.EmployeeID,
		arg.SubjectID,
		arg.ScopeJson,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i UserRoleAssignment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.FoundationID,
		&i.SchoolID,
		&i.ClassID,
		&i.StudentID,
		&i.EmployeeID,
		&i.SubjectID,
		&i.ScopeJson,
		&i.IsActive,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, code, name, description, is_system, created_at, updated_at
FROM roles
WHERE code = $1
`

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserContextAssignments = `-- name: GetUserContextAssignments :many
SELECT
    ura.id AS assignment_id,
    ura.user_id,
    r.code AS role_code,
    ura.foundation_id,
    ura.school_id,
    ura.class_id,
    ura.student_id,
    ura.employee_id,
    ura.subject_id,
    ura.scope_json,
    ura.starts_at,
    ura.ends_at,
    COALESCE(
        ARRAY_AGG(DISTINCT p.code ORDER BY p.code) FILTER (WHERE p.code IS NOT NULL),
        ARRAY[]::VARCHAR[]
    )::TEXT[] AS permission_codes
FROM user_role_assignments ura
JOIN roles r ON r.id = ura.role_id
LEFT JOIN role_permissions rp ON rp.role_id = r.id
LEFT JOIN permissions p ON p.id = rp.permission_id
WHERE ura.user_id = $1
  AND ura.is_active = TRUE
  AND (ura.starts_at IS NULL OR ura.starts_at <= $2)
  AND (ura.ends_at IS NULL OR ura.ends_at > $2)
GROUP BY ura.id, r.code
ORDER BY r.code, ura.foundation_id, ura.school_id, ura.class_id, ura.student_id, ura.subject_id
`

type GetUserContextAssignmentsParams struct {
	UserID   uuid.UUID          `json:"user_id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

type GetUserContextAssignmentsRow struct {
	AssignmentID    uuid.UUID          `json:"assignment_id"`
	UserID          uuid.UUID          `json:"user_id"`
	RoleCode        string             `json:"role_code"`
	FoundationID    uuid.UUID          `json:"foundation_id"`
	SchoolID        *uuid.UUID         `json:"school_id"`
	ClassID         *uuid.UUID         `json:"class_id"`
	StudentID       *uuid.UUID         `json:"student_id"`
	EmployeeID      *uuid.UUID         `json:"employee_id"`
	SubjectID       *uuid.UUID         `json:"subject_id"`
	ScopeJson       []byte             `json:"scope_json"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	PermissionCodes []string           `json:"permission_codes"`
}

func (q *Queries) GetUserContextAssignments(ctx context.Context, arg GetUserContextAssignmentsParams) ([]GetUserContextAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, getUserContextAssignments, arg.UserID, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserContextAssignmentsRow{}
	for rows.Next() {
		var i GetUserContextAssignmentsRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.UserID,
			&i.RoleCode,
			&i.FoundationID,
			&i.SchoolID,
			&i.ClassID,
			&i.StudentID,
			&i.EmployeeID,
			&i.SubjectID,
			&i.ScopeJson,
			&i.StartsAt,
			&i.EndsAt,
			&i.PermissionCodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
