// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbsqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityAuditLog struct {
	ID            uuid.UUID          `json:"id"`
	FoundationID  uuid.UUID          `json:"foundation_id"`
	SchoolID      *uuid.UUID         `json:"school_id"`
	ActorUserID   *uuid.UUID         `json:"actor_user_id"`
	ActorRole     *string            `json:"actor_role"`
	Action        string             `json:"action"`
	Module        string             `json:"module"`
	EntityType    string             `json:"entity_type"`
	EntityID      uuid.UUID          `json:"entity_id"`
	OldValuesJson []byte             `json:"old_values_json"`
	NewValuesJson []byte             `json:"new_values_json"`
	MetadataJson  []byte             `json:"metadata_json"`
	IpAddress     *string            `json:"ip_address"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	RequestID     string             `json:"request_id"`
	CorrelationID string             `json:"correlation_id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID          uuid.UUID          `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Module      string             `json:"module"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          uuid.UUID          `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	ID           uuid.UUID          `json:"id"`
	RoleID       uuid.UUID          `json:"role_id"`
	PermissionID uuid.UUID          `json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	Phone        *string            `json:"phone"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	AvatarFileID *uuid.UUID         `json:"avatar_file_id"`
	Status       string             `json:"status"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserDevice struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	DeviceUid  string             `json:"device_uid"`
	Platform   string             `json:"platform"`
	DeviceName *string            `json:"device_name"`
	FcmToken   pgtype.Text        `json:"fcm_token"`
	IsActive   bool               `json:"is_active"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type UserRoleAssignment struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	RoleID       uuid.UUID          `json:"role_id"`
	FoundationID uuid.UUID          `json:"foundation_id"`
	SchoolID     *uuid.UUID         `json:"school_id"`
	ClassID      *uuid.UUID         `json:"class_id"`
	StudentID    *uuid.UUID         `json:"student_id"`
	EmployeeID   *uuid.UUID         `json:"employee_id"`
	SubjectID    *uuid.UUID         `json:"subject_id"`
	ScopeJson    []byte             `json:"scope_json"`
	IsActive     bool               `json:"is_active"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	EndsAt       pgtype.Timestamptz `json:"ends_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserSession struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	DeviceID         *uuid.UUID         `json:"device_id"`
	IpAddress        *string            `json:"ip_address"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
