// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    email,
    phone,
    password_hash,
    display_name,
    avatar_file_id,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, email, phone, password_hash, display_name, avatar_file_id, status,
    last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID  `json:"id"`
	Email        string     `json:"email"`
	Phone        *string    `json:"phone"`
	PasswordHash string     `json:"password_hash"`
	DisplayName  string     `json:"display_name"`
	AvatarFileID *uuid.UUID `json:"avatar_file_id"`
	Status       string     `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.DisplayName,
		arg.AvatarFileID,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone, password_hash, display_name, avatar_file_id, status,
    last_login_at, created_at, updated_at
FROM users
WHERE LOWER(email) = LOWER($1)
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone, password_hash, display_name, avatar_file_id, status,
    last_login_at, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :one
UPDATE users
SET last_login_at = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, phone, password_hash, display_name, avatar_file_id, status,
    last_login_at, created_at, updated_at
`

type UpdateUserLastLoginParams struct {
	ID          uuid.UUID          `json:"id"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLastLogin, arg.ID, arg.LastLoginAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, phone, password_hash, display_name, avatar_file_id, status,
    last_login_at, created_at, updated_at
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
