// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbsqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AcademicYear struct {
	ID           uuid.UUID          `json:"id"`
	FoundationID uuid.UUID          `json:"foundation_id"`
	Name         string             `json:"name"`
	StartDate    pgtype.Date        `json:"start_date"`
	EndDate      pgtype.Date        `json:"end_date"`
	Status       string             `json:"status"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID            uuid.UUID          `json:"id"`
	FoundationID  uuid.UUID          `json:"foundation_id"`
	SchoolID      *uuid.UUID         `json:"school_id"`
	ActorUserID   *uuid.UUID         `json:"actor_user_id"`
	ActorRole     *string            `json:"actor_role"`
	Action        string             `json:"action"`
	Module        string             `json:"module"`
	EntityType    string             `json:"entity_type"`
	EntityID      uuid.UUID          `json:"entity_id"`
	OldValuesJson []byte             `json:"old_values_json"`
	NewValuesJson []byte             `json:"new_values_json"`
	MetadataJson  []byte             `json:"metadata_json"`
	IpAddress     *string            `json:"ip_address"`
	UserAgent     *string            `json:"user_agent"`
	RequestID     string             `json:"request_id"`
	CorrelationID string             `json:"correlation_id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Class struct {
	ID             uuid.UUID          `json:"id"`
	FoundationID   uuid.UUID          `json:"foundation_id"`
	SchoolID       uuid.UUID          `json:"school_id"`
	AcademicYearID uuid.UUID          `json:"academic_year_id"`
	GradeLevelID   uuid.UUID          `json:"grade_level_id"`
	ClassCode      string             `json:"class_code"`
	Name           string             `json:"name"`
	Capacity       pgtype.Int4        `json:"capacity"`
	RoomID         *uuid.UUID         `json:"room_id"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Foundation struct {
	ID             uuid.UUID          `json:"id"`
	FoundationCode string             `json:"foundation_code"`
	Name           string             `json:"name"`
	LegalName      *string            `json:"legal_name"`
	Address        *string            `json:"address"`
	Phone          *string            `json:"phone"`
	Email          *string            `json:"email"`
	LogoFileID     *uuid.UUID         `json:"logo_file_id"`
	Timezone       string             `json:"timezone"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type GradeLevel struct {
	ID           uuid.UUID          `json:"id"`
	FoundationID uuid.UUID          `json:"foundation_id"`
	SchoolID     uuid.UUID          `json:"school_id"`
	LevelCode    string             `json:"level_code"`
	Name         string             `json:"name"`
	Sequence     int32              `json:"sequence"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Guardian struct {
	ID               uuid.UUID          `json:"id"`
	FoundationID     uuid.UUID          `json:"foundation_id"`
	FullName         string             `json:"full_name"`
	RelationshipType string             `json:"relationship_type"`
	Phone            *string            `json:"phone"`
	Email            *string            `json:"email"`
	Address          *string            `json:"address"`
	Occupation       *string            `json:"occupation"`
	UserID           *uuid.UUID         `json:"user_id"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type HomeroomAssignment struct {
	ID             uuid.UUID          `json:"id"`
	FoundationID   uuid.UUID          `json:"foundation_id"`
	SchoolID       uuid.UUID          `json:"school_id"`
	AcademicYearID uuid.UUID          `json:"academic_year_id"`
	SemesterID     *uuid.UUID         `json:"semester_id"`
	TeacherID      uuid.UUID          `json:"teacher_id"`
	ClassID        uuid.UUID          `json:"class_id"`
	Status         string             `json:"status"`
	ApprovedBy     *uuid.UUID         `json:"approved_by"`
	ApprovedAt     pgtype.Timestamptz `json:"approved_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OutboxEvent struct {
	ID            uuid.UUID          `json:"id"`
	EventID       uuid.UUID          `json:"event_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   uuid.UUID          `json:"aggregate_id"`
	PayloadJson   []byte             `json:"payload_json"`
	Status        string             `json:"status"`
	RetryCount    int32              `json:"retry_count"`
	NextRetryAt   pgtype.Timestamptz `json:"next_retry_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Room struct {
	ID           uuid.UUID          `json:"id"`
	FoundationID uuid.UUID          `json:"foundation_id"`
	SchoolID     uuid.UUID          `json:"school_id"`
	RoomCode     string             `json:"room_code"`
	Name         string             `json:"name"`
	Capacity     pgtype.Int4        `json:"capacity"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type School struct {
	ID           uuid.UUID          `json:"id"`
	FoundationID uuid.UUID          `json:"foundation_id"`
	SchoolCode   string             `json:"school_code"`
	Name         string             `json:"name"`
	SchoolLevel  string             `json:"school_level"`
	Npsn         *string            `json:"npsn"`
	Address      *string            `json:"address"`
	Phone        *string            `json:"phone"`
	Email        *string            `json:"email"`
	LogoFileID   *uuid.UUID         `json:"logo_file_id"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Semester struct {
	ID             uuid.UUID          `json:"id"`
	FoundationID   uuid.UUID          `json:"foundation_id"`
	AcademicYearID uuid.UUID          `json:"academic_year_id"`
	Name           string             `json:"name"`
	Sequence       int32              `json:"sequence"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	Status         string             `json:"status"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Student struct {
	ID            uuid.UUID          `json:"id"`
	FoundationID  uuid.UUID          `json:"foundation_id"`
	SchoolID      uuid.UUID          `json:"school_id"`
	StudentNumber *string            `json:"student_number"`
	Nisn          *string            `json:"nisn"`
	FullName      string             `json:"full_name"`
	Gender        string             `json:"gender"`
	BirthPlace    *string            `json:"birth_place"`
	BirthDate     pgtype.Date        `json:"birth_date"`
	Religion      *string            `json:"religion"`
	Address       *string            `json:"address"`
	Phone         *string            `json:"phone"`
	Email         *string            `json:"email"`
	PhotoFileID   *uuid.UUID         `json:"photo_file_id"`
	Status        string             `json:"status"`
	EntryYear     pgtype.Int4        `json:"entry_year"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type StudentClassAssignment struct {
	ID             uuid.UUID          `json:"id"`
	FoundationID   uuid.UUID          `json:"foundation_id"`
	SchoolID       uuid.UUID          `json:"school_id"`
	AcademicYearID uuid.UUID          `json:"academic_year_id"`
	SemesterID     *uuid.UUID         `json:"semester_id"`
	StudentID      uuid.UUID          `json:"student_id"`
	ClassID        uuid.UUID          `json:"class_id"`
	Status         string             `json:"status"`
	AssignedAt     pgtype.Timestamptz `json:"assigned_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type StudentGuardian struct {
	ID                     uuid.UUID          `json:"id"`
	FoundationID           uuid.UUID          `json:"foundation_id"`
	StudentID              uuid.UUID          `json:"student_id"`
	GuardianID             uuid.UUID          `json:"guardian_id"`
	RelationshipType       string             `json:"relationship_type"`
	IsPrimary              bool               `json:"is_primary"`
	CanLogin               bool               `json:"can_login"`
	CanReceiveNotification bool               `json:"can_receive_notification"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type Teacher struct {
	ID               uuid.UUID          `json:"id"`
	FoundationID     uuid.UUID          `json:"foundation_id"`
	SchoolID         uuid.UUID          `json:"school_id"`
	EmployeeNumber   *string            `json:"employee_number"`
	UserID           *uuid.UUID         `json:"user_id"`
	FullName         string             `json:"full_name"`
	Gender           *string            `json:"gender"`
	BirthPlace       *string            `json:"birth_place"`
	BirthDate        pgtype.Date        `json:"birth_date"`
	Email            *string            `json:"email"`
	Phone            *string            `json:"phone"`
	Address          *string            `json:"address"`
	PhotoFileID      *uuid.UUID         `json:"photo_file_id"`
	EmploymentStatus *string            `json:"employment_status"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type TeacherAssignment struct {
	ID             uuid.UUID          `json:"id"`
	FoundationID   uuid.UUID          `json:"foundation_id"`
	SchoolID       uuid.UUID          `json:"school_id"`
	AcademicYearID uuid.UUID          `json:"academic_year_id"`
	SemesterID     uuid.UUID          `json:"semester_id"`
	TeacherID      uuid.UUID          `json:"teacher_id"`
	ClassID        *uuid.UUID         `json:"class_id"`
	SubjectID      *uuid.UUID         `json:"subject_id"`
	AssignmentType string             `json:"assignment_type"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
