// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: schools.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
    id, foundation_id, school_id, actor_user_id, actor_role, action, module,
    entity_type, entity_id, old_values_json, new_values_json, metadata_json,
    ip_address, user_agent, request_id, correlation_id, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
`

type CreateAuditLogParams struct {
	ID            uuid.UUID          `json:"id"`
	FoundationID  uuid.UUID          `json:"foundation_id"`
	SchoolID      *uuid.UUID         `json:"school_id"`
	ActorUserID   *uuid.UUID         `json:"actor_user_id"`
	ActorRole     *string            `json:"actor_role"`
	Action        string             `json:"action"`
	Module        string             `json:"module"`
	EntityType    string             `json:"entity_type"`
	EntityID      uuid.UUID          `json:"entity_id"`
	OldValuesJson []byte             `json:"old_values_json"`
	NewValuesJson []byte             `json:"new_values_json"`
	MetadataJson  []byte             `json:"metadata_json"`
	IpAddress     *string            `json:"ip_address"`
	UserAgent     *string            `json:"user_agent"`
	RequestID     string             `json:"request_id"`
	CorrelationID string             `json:"correlation_id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ID,
		arg.FoundationID,
		arg.SchoolID,
		arg.ActorUserID,
		arg.ActorRole,
		arg.Action,
		arg.Module,
		arg.EntityType,
		arg.EntityID,
		arg.OldValuesJson,
		arg.NewValuesJson,
		arg.MetadataJson,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
		arg.CorrelationID,
		arg.OccurredAt,
	)
	return err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (
    id, event_id, event_type, event_version, aggregate_type, aggregate_id, payload_json
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOutboxEventParams struct {
	ID            uuid.UUID `json:"id"`
	EventID       uuid.UUID `json:"event_id"`
	EventType     string    `json:"event_type"`
	EventVersion  int32     `json:"event_version"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	PayloadJson   []byte    `json:"payload_json"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent,
		arg.ID,
		arg.EventID,
		arg.EventType,
		arg.EventVersion,
		arg.AggregateType,
		arg.AggregateID,
		arg.PayloadJson,
	)
	return err
}

const createSchool = `-- name: CreateSchool :one
INSERT INTO schools (
    id, foundation_id, school_code, name, school_level, npsn, address,
    phone, email, logo_file_id, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, foundation_id, school_code, name, school_level, npsn, address, phone, email, logo_file_id, status, created_at, updated_at
`

type CreateSchoolParams struct {
	ID           uuid.UUID  `json:"id"`
	FoundationID uuid.UUID  `json:"foundation_id"`
	SchoolCode   string     `json:"school_code"`
	Name         string     `json:"name"`
	SchoolLevel  string     `json:"school_level"`
	Npsn         *string    `json:"npsn"`
	Address      *string    `json:"address"`
	Phone        *string    `json:"phone"`
	Email        *string    `json:"email"`
	LogoFileID   *uuid.UUID `json:"logo_file_id"`
	Status       string     `json:"status"`
}

func (q *Queries) CreateSchool(ctx context.Context, arg CreateSchoolParams) (School, error) {
	row := q.db.QueryRow(ctx, createSchool,
		arg.ID,
		arg.FoundationID,
		arg.SchoolCode,
		arg.Name,
		arg.SchoolLevel,
		arg.Npsn,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.LogoFileID,
		arg.Status,
	)
	var i School
	err := row.Scan(
		&i.ID,
		&i.FoundationID,
		&i.SchoolCode,
		&i.Name,
		&i.SchoolLevel,
		&i.Npsn,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.LogoFileID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFoundationByID = `-- name: GetFoundationByID :one
SELECT id, foundation_code, name, legal_name, address, phone, email, logo_file_id, timezone, status, created_at, updated_at FROM foundations WHERE id = $1
`

func (q *Queries) GetFoundationByID(ctx context.Context, id uuid.UUID) (Foundation, error) {
	row := q.db.QueryRow(ctx, getFoundationByID, id)
	var i Foundation
	err := row.Scan(
		&i.ID,
		&i.FoundationCode,
		&i.Name,
		&i.LegalName,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.LogoFileID,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSchoolByScope = `-- name: GetSchoolByScope :one
SELECT id, foundation_id, school_code, name, school_level, npsn, address, phone, email, logo_file_id, status, created_at, updated_at FROM schools WHERE id = $1 AND foundation_id = $2
`

type GetSchoolByScopeParams struct {
	ID           uuid.UUID `json:"id"`
	FoundationID uuid.UUID `json:"foundation_id"`
}

func (q *Queries) GetSchoolByScope(ctx context.Context, arg GetSchoolByScopeParams) (School, error) {
	row := q.db.QueryRow(ctx, getSchoolByScope, arg.ID, arg.FoundationID)
	var i School
	err := row.Scan(
		&i.ID,
		&i.FoundationID,
		&i.SchoolCode,
		&i.Name,
		&i.SchoolLevel,
		&i.Npsn,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.LogoFileID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchoolsByFoundation = `-- name: ListSchoolsByFoundation :many
SELECT id, foundation_id, school_code, name, school_level, npsn, address, phone, email, logo_file_id, status, created_at, updated_at FROM schools WHERE foundation_id = $1 ORDER BY school_code, id
`

func (q *Queries) ListSchoolsByFoundation(ctx context.Context, foundationID uuid.UUID) ([]School, error) {
	rows, err := q.db.Query(ctx, listSchoolsByFoundation, foundationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.FoundationID,
			&i.SchoolCode,
			&i.Name,
			&i.SchoolLevel,
			&i.Npsn,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.LogoFileID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchool = `-- name: UpdateSchool :one
UPDATE schools SET
    school_code = $3,
    name = $4,
    school_level = $5,
    npsn = $6,
    address = $7,
    phone = $8,
    email = $9,
    logo_file_id = $10,
    status = $11,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND foundation_id = $2
RETURNING id, foundation_id, school_code, name, school_level, npsn, address, phone, email, logo_file_id, status, created_at, updated_at
`

type UpdateSchoolParams struct {
	ID           uuid.UUID  `json:"id"`
	FoundationID uuid.UUID  `json:"foundation_id"`
	SchoolCode   string     `json:"school_code"`
	Name         string     `json:"name"`
	SchoolLevel  string     `json:"school_level"`
	Npsn         *string    `json:"npsn"`
	Address      *string    `json:"address"`
	Phone        *string    `json:"phone"`
	Email        *string    `json:"email"`
	LogoFileID   *uuid.UUID `json:"logo_file_id"`
	Status       string     `json:"status"`
}

func (q *Queries) UpdateSchool(ctx context.Context, arg UpdateSchoolParams) (School, error) {
	row := q.db.QueryRow(ctx, updateSchool,
		arg.ID,
		arg.FoundationID,
		arg.SchoolCode,
		arg.Name,
		arg.SchoolLevel,
		arg.Npsn,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.LogoFileID,
		arg.Status,
	)
	var i School
	err := row.Scan(
		&i.ID,
		&i.FoundationID,
		&i.SchoolCode,
		&i.Name,
		&i.SchoolLevel,
		&i.Npsn,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.LogoFileID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
